name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app and create DMG
        run: |
          xcodebuild -scheme LoopSmith -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO
          mkdir dmg
          cp -R build/Build/Products/Release/LoopSmith.app dmg/
          hdiutil create -volname LoopSmith -srcfolder dmg -ov -format UDZO LoopSmith-${GITHUB_REF_NAME}.dmg
      - name: Upload DMG to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN_WITH_REPO_SCOPE }}
          files: LoopSmith-${{ github.ref_name }}.dmg